version: '3.9'

services:
  dyssomnia-scanner:
    container_name: dyssomnia-scanner
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - dyssomnia-scanner-db
    networks:
      - dyssomnia-network

  dyssomnia-scanner-db:
    container_name: dyssomnia_dbz
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - dyssomniaDbVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    command: -p ${DB_PORT}
    networks:
      - dyssomnia-network

volumes:
  dyssomniaDbVolume:
    driver: local

networks:
  dyssomnia-network:
    name: dyssomnia-network